stryker4s {
  mutate: [
    "**/src/main/scala/co/uproot/abandon/Ast.scala",
    "**/src/main/scala/co/uproot/abandon/Eval.scala",
    "**/src/main/scala/co/uproot/abandon/Helper.scala",
    "**/src/main/scala/co/uproot/abandon/Parser.scala"
  ]
  test-filter: ["!co.uproot.abandon.FileWatcherTest"]
  excluded-mutations: ["MethodExpression"]
  scala-dialect: "scala3"
  reporters: ["html", "console"]
  thresholds {
    high = 80
    low = 60
    break = 0
  }
}
